### ISSUE TITLE
List of jokes

### ISSUE THREAD

**Issue by badabam** [badabam/jokes-app-hh-web-22-1#2]
## Value proposition

**As a** reader
**I need** to have a list of jokes
**to be able to** have a good laugh

## Description
<img width="200" src=https://user-images.githubusercontent.com/157286/156532049-4136122e-fbcb-498c-9af3-619af3d92b0e.png />

## Acceptance Criteria

- [x] the list is scrollable

## Tasks

- [x] components/Joke
    - [x] Storybook
    - [x] Tests
- [x] Add list of Jokes in App
- [x] Update global styles
- [x] Test on mobile device
